### ISSUE TITLE
Implement Lightning Data

### ISSUE THREAD

**Issue by zaskem** [zaskem/slackbot-tempestweather#1]
Data regarding lightning activity is readily available from the Tempest API, but requires additional processing.

Create something interesting with lightning data (push notification) or the like. Somehow implement into the bot source.

**Comment by pickettbrass** [comment]
This would be of great use to me - having a slack channel that has instantaneous messages on lightening events.  IFTTT's link doesn't work well, if at all, and certainly isn't real time.  Thank you for working on this!
